-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List current monitors and supported resolutions with: hyprctl monitors all
-- Monitor selection/arrangement below is generated by linux/configure-monitors.sh.
-- Rerun that script any time your monitor setup changes.

local omarchy_gdk_scale = 2
local omarchy_monitor_scale = "auto"

hl.env("GDK_SCALE", tostring(omarchy_gdk_scale))

-- Fallback for any monitor without an explicit rule below (e.g. one
-- plugged into a port that's never been seen before, or one you chose
-- not to configure above). Leaving output empty makes this a
-- catch-all per the docs.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = omarchy_monitor_scale })

-- Chosen via configure-monitors.sh: which outputs to configure, and
-- their position. First entry is the main monitor, at 0x0; the rest
-- chain to its right in the order picked.
local configured_positions = {
  ["DP-1"] = "0x0",
  ["HDMI-A-1"] = "auto-right",
}

-- Pin every currently-connected, configured monitor to its true max
-- mode: highest resolution, then highest refresh rate available at that
-- resolution. Hyprland's own "preferred" mode follows the EDID-flagged
-- preferred timing, which is often a lower refresh rate than the panel
-- actually supports, and the built-in "highres"/"highrr" mode values
-- only optimize one dimension each. Uses hl.get_monitors() (in-process)
-- rather than shelling out to `hyprctl`, since calling back into
-- Hyprland's own IPC from inside its synchronous config load can
-- deadlock the compositor.
for _, mon in ipairs(hl.get_monitors()) do
  local position = configured_positions[mon.name]

  if position then
    local best = nil

    for _, m in ipairs(mon.available_modes) do
      if not best
          or (m.width * m.height > best.width * best.height)
          or (m.width * m.height == best.width * best.height and m.refresh_rate > best.refresh_rate) then
        best = m
      end
    end

    if best then
      hl.monitor({
        output = mon.name,
        mode = string.format("%dx%d@%.2f", best.width, best.height, best.refresh_rate),
        position = position,
        scale = omarchy_monitor_scale,
      })
    end
  end
end

-- 5 workspaces per monitor, in the order picked: main gets 1-5,
-- the next monitor 6-10, and so on. Keeps the top bar's per-monitor
-- workspace ranges (workspaces-per-monitor.qml) and SUPER+N in sync
-- with what's actually bound to each screen.
hl.workspace_rule({ workspace = "1", monitor = "DP-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "DP-1", default = false, persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "DP-1", default = false, persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "DP-1", default = false, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "DP-1", default = false, persistent = true })
hl.workspace_rule({ workspace = "6", monitor = "HDMI-A-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "HDMI-A-1", default = false, persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "HDMI-A-1", default = false, persistent = true })
hl.workspace_rule({ workspace = "9", monitor = "HDMI-A-1", default = false, persistent = true })
hl.workspace_rule({ workspace = "10", monitor = "HDMI-A-1", default = false, persistent = true })
