#!/usr/bin/env bash

# Interactively choose which connected monitors to configure and which one
# is the main (positioned at 0x0, with the rest chained to its right), then
# regenerate linux/.config/hypr/monitors.lua accordingly. Every monitor
# chosen here still gets pinned to its true max mode (highest resolution,
# then highest refresh rate at that resolution) automatically on every
# Hyprland start/reload — that part isn't re-run by this script, it's
# baked into the generated config.
#
# When 2+ monitors are chosen, workspaces are also split 5-per-monitor in
# picked order (main: 1-5, next: 6-10, ...) via hl.workspace_rule, and the
# top bar's workspace widget is swapped for a custom one (see
# .config/omarchy/bar/modules/workspaces-per-monitor.qml) that only shows
# each monitor's own range instead of the same global range on every
# screen. With a single monitor chosen, both are left as Hyprland/Omarchy's
# defaults (or reverted to them, if a previous run had set up the split).
#
# Rerun this script any time your monitor setup changes (new monitor,
# different arrangement, etc).

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/log.sh"

MONITORS_LUA="$SCRIPT_DIR/.config/hypr/monitors.lua"
SHELL_JSON="$HOME/.config/omarchy/shell.json"
WORKSPACES_WIDGET_ID="workspaces-per-monitor"

if ! command -v hyprctl &>/dev/null || ! hyprctl monitors -j &>/dev/null; then
  log "Hyprland doesn't seem to be running; skipping interactive monitor setup."
  exit 0
fi

monitors_json=$(hyprctl monitors -j)

mapfile -t names < <(echo "$monitors_json" | jq -r '.[].name')

if (( ${#names[@]} == 0 )); then
  log "No monitors detected; skipping interactive monitor setup."
  exit 0
fi

mapfile -t labels < <(echo "$monitors_json" | jq -r '.[] | "\(.name) — \(.description) (\(.width)x\(.height)@\(.refreshRate)Hz)"')

declare -A label_to_name
for i in "${!names[@]}"; do
  label_to_name["${labels[$i]}"]="${names[$i]}"
done

log "Detected ${#names[@]} monitor(s)."

selected="$(gum choose --no-limit --select-if-one --header "Which monitor(s) do you want to configure?" "${labels[@]}")"

if [[ -z "$selected" ]]; then
  log "No monitors selected; leaving monitors.lua unchanged."
  exit 0
fi

mapfile -t selected_labels <<< "$selected"

main_label="$(printf '%s\n' "${selected_labels[@]}" | gum choose --select-if-one --header "Which one is your main monitor?")"

# Reorder so main is first: it gets 0x0, the rest chain auto-right in the
# order they were picked.
ordered_labels=("$main_label")
for l in "${selected_labels[@]}"; do
  [[ "$l" != "$main_label" ]] && ordered_labels+=("$l")
done

multi=false
(( ${#ordered_labels[@]} >= 2 )) && multi=true

# 5 workspaces per monitor, in picked order: main gets 1-5, the next 6-10,
# and so on. Only meaningful (and only generated) when multi is true.
ranges_json="{}"
workspace_rules=""
start=1
for label in "${ordered_labels[@]}"; do
  name="${label_to_name[$label]}"
  if [[ "$multi" == true ]]; then
    ids="[$start,$((start + 1)),$((start + 2)),$((start + 3)),$((start + 4))]"
    ranges_json="$(jq --arg name "$name" --argjson ids "$ids" '. + {($name): $ids}' <<< "$ranges_json")"

    for offset in 0 1 2 3 4; do
      ws=$((start + offset))
      is_default="false"
      (( offset == 0 )) && is_default="true"
      workspace_rules+="hl.workspace_rule({ workspace = \"$ws\", monitor = \"$name\", default = $is_default, persistent = true })"$'\n'
    done
  fi
  start=$((start + 5))
done

{
  echo "-- See https://wiki.hypr.land/Configuring/Basics/Monitors/"
  echo "-- List current monitors and supported resolutions with: hyprctl monitors all"
  echo "-- Monitor selection/arrangement below is generated by linux/configure-monitors.sh."
  echo "-- Rerun that script any time your monitor setup changes."
  echo
  echo 'local omarchy_gdk_scale = 2'
  echo 'local omarchy_monitor_scale = "auto"'
  echo
  echo 'hl.env("GDK_SCALE", tostring(omarchy_gdk_scale))'
  echo
  echo "-- Fallback for any monitor without an explicit rule below (e.g. one"
  echo "-- plugged into a port that's never been seen before, or one you chose"
  echo "-- not to configure above). Leaving output empty makes this a"
  echo "-- catch-all per the docs."
  echo 'hl.monitor({ output = "", mode = "preferred", position = "auto", scale = omarchy_monitor_scale })'
  echo
  echo "-- Chosen via configure-monitors.sh: which outputs to configure, and"
  echo "-- their position. First entry is the main monitor, at 0x0; the rest"
  echo "-- chain to its right in the order picked."
  echo "local configured_positions = {"
  for i in "${!ordered_labels[@]}"; do
    name="${label_to_name[${ordered_labels[$i]}]}"
    if (( i == 0 )); then
      pos="0x0"
    else
      pos="auto-right"
    fi
    printf '  ["%s"] = "%s",\n' "$name" "$pos"
  done
  echo "}"
  echo
  cat <<'LUA'
-- Pin every currently-connected, configured monitor to its true max
-- mode: highest resolution, then highest refresh rate available at that
-- resolution. Hyprland's own "preferred" mode follows the EDID-flagged
-- preferred timing, which is often a lower refresh rate than the panel
-- actually supports, and the built-in "highres"/"highrr" mode values
-- only optimize one dimension each. Uses hl.get_monitors() (in-process)
-- rather than shelling out to `hyprctl`, since calling back into
-- Hyprland's own IPC from inside its synchronous config load can
-- deadlock the compositor.
for _, mon in ipairs(hl.get_monitors()) do
  local position = configured_positions[mon.name]

  if position then
    local best = nil

    for _, m in ipairs(mon.available_modes) do
      if not best
          or (m.width * m.height > best.width * best.height)
          or (m.width * m.height == best.width * best.height and m.refresh_rate > best.refresh_rate) then
        best = m
      end
    end

    if best then
      hl.monitor({
        output = mon.name,
        mode = string.format("%dx%d@%.2f", best.width, best.height, best.refresh_rate),
        position = position,
        scale = omarchy_monitor_scale,
      })
    end
  end
end
LUA

  if [[ "$multi" == true ]]; then
    echo
    echo "-- 5 workspaces per monitor, in the order picked: main gets 1-5,"
    echo "-- the next monitor 6-10, and so on. Keeps the top bar's per-monitor"
    echo "-- workspace ranges (workspaces-per-monitor.qml) and SUPER+N in sync"
    echo "-- with what's actually bound to each screen."
    printf '%s' "$workspace_rules"
  fi
} > "$MONITORS_LUA"

log "Wrote $MONITORS_LUA for: ${ordered_labels[*]}"

# Swap the bar's workspace widget for the per-monitor one (and back again)
# to match. shell.json is the user's canonical, hand-editable bar config —
# not dotfiles-tracked — so this patches only the workspaces entry in place
# rather than overwriting the file.
shell_json_changed=false
if [[ -f "$SHELL_JSON" ]]; then
  new_shell_json="$(jq \
    --argjson ranges "$ranges_json" \
    --arg widgetId "$WORKSPACES_WIDGET_ID" \
    --argjson multi "$multi" \
    '
      def swap:
        if $multi and .id == "omarchy.workspaces" then
          {"id": $widgetId, "type": "qml", "ranges": $ranges}
        elif $multi and .id == $widgetId then
          {"id": $widgetId, "type": "qml", "ranges": $ranges}
        elif ($multi | not) and .id == $widgetId then
          {"id": "omarchy.workspaces"}
        else
          .
        end;
      .bar.layout.left = (.bar.layout.left // [] | map(swap)) |
      .bar.layout.center = (.bar.layout.center // [] | map(swap)) |
      .bar.layout.right = (.bar.layout.right // [] | map(swap))
    ' "$SHELL_JSON")"

  if [[ "$new_shell_json" != "$(cat "$SHELL_JSON")" ]]; then
    printf '%s\n' "$new_shell_json" > "$SHELL_JSON"
    shell_json_changed=true
    log "Updated $SHELL_JSON's workspaces widget."
  fi
else
  log "No $SHELL_JSON yet; leaving the bar on Omarchy's default workspaces widget."
fi

hyprctl reload &>/dev/null || true

if [[ "$shell_json_changed" == true ]] && command -v omarchy-restart-shell &>/dev/null; then
  omarchy-restart-shell &>/dev/null || true
fi
